// <auto-generated />
using DDD.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDD.Infrastructure.Migrations
{
    [DbContext(typeof(WebLocalizeDbContext))]
    [Migration("20251130180600_AtualizaSituacaoCampos")]
    partial class AtualizaSituacaoCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DDD.Infrastructure.Entities.Cidade", b =>
                {
                    b.Property<int>("CIDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CIDID"));

                    b.Property<string>("CIDNOME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CIDSITUACAO")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("CIDUF")
                        .HasColumnType("int");

                    b.HasKey("CIDID");

                    b.HasIndex("CIDUF");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("DDD.Infrastructure.Entities.Estado", b =>
                {
                    b.Property<int>("UFID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UFID"));

                    b.Property<string>("UFNOME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UFSIGLA")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UFSITUACAO")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("UFID");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("DDD.Infrastructure.Entities.Local", b =>
                {
                    b.Property<int>("LOCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LOCID"));

                    b.Property<int>("LOCCID")
                        .HasColumnType("int");

                    b.Property<string>("LOCNOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LOCSITUACAO")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("LOCUF")
                        .HasColumnType("int");

                    b.HasKey("LOCID");

                    b.HasIndex("LOCCID");

                    b.HasIndex("LOCUF");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("DDD.Infrastructure.Entities.Cidade", b =>
                {
                    b.HasOne("DDD.Infrastructure.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("CIDUF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("DDD.Infrastructure.Entities.Local", b =>
                {
                    b.HasOne("DDD.Infrastructure.Entities.Cidade", "Cidade")
                        .WithMany("Locais")
                        .HasForeignKey("LOCCID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DDD.Infrastructure.Entities.Estado", "Estado")
                        .WithMany("Locais")
                        .HasForeignKey("LOCUF")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("DDD.Infrastructure.Entities.Cidade", b =>
                {
                    b.Navigation("Locais");
                });

            modelBuilder.Entity("DDD.Infrastructure.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");

                    b.Navigation("Locais");
                });
#pragma warning restore 612, 618
        }
    }
}
